version: '3.8'

services:
  copilot_api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: copilot_job_api
    restart: always
    depends_on:
      - postgres
    networks:
      - copilot-network
    env_file:
      - .env
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - copilot-network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - copilot-network

networks:
  copilot-network:
    driver: bridge

volumes:
  pg_data:
