version: '3.8'

services:
  copilot_api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: copilot_job_api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/copilot
    entrypoint: ["sh", "-c", "chmod +x /copilot/.docker/entrypoint.sh && /copilot/.docker/entrypoint.sh"]



networks:
  default:
    name: longman_network
    external: true
